### ISSUE TITLE
linker command failed with exit code 1

### ISSUE THREAD

**Issue by szwacz** [LinusU/fs-xattr#10]
Hello, I'm  getting this error when trying to install. Should I have some third party tools on my machine for installation to succeed?
```
npm install fs-xattr

> fs-xattr@0.1.11 install /node_modules/fs-xattr
> node-gyp rebuild

  CXX(target) Release/obj.target/xattr/src/error.o
  CXX(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/xattr.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/xattr.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/fs-xattr
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install" "fs-xattr"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! fs-xattr@0.1.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fs-xattr@0.1.11 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fs-xattr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fs-xattr
npm ERR! There is likely additional logging output above.
```

**Comment by LinusU** [comment]
Hmm, I think I've seen this before... Could you try and run `xcode-select --install`?

**Comment by LinusU** [comment]
Hmm, that's too bad. Unfortunately I don't really have any clues :(

Which version of OS X do you run? Is Xcode installed thru the app store? if so, which version?

**Comment by szwacz** [comment]
Yes! That was it: too old xcode. Had version 6.2 and problem disappeared after upgrading to 7.
Thanks!
