### ISSUE TITLE
The named attribute is not permitted for this type of object.

### ISSUE THREAD

**Issue by Leaking** [LinusU/fs-xattr#28]
I run the below script (i use fs-xattr 0.2.1 and my mac is 10.14.4 )
```
xattr.setSync(filepath, 'com.XXdrive.at', 'com.XXdrive.value')
```

and get this error

```
Error: The named attribute is not permitted for this type of object.
    at Object.setSync (/Users/quinn/Documents/workspace/node/nodebook/node_modules/fs-xattr/index.js:79:16)
    at Object.<anonymous> (/Users/quinn/Documents/workspace/node/nodebook/xattrtest.js:7:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by LinusU** [comment]
Which file system is the file you are operating on on?

**Comment by Leaking** [comment]
@LinusU  My mac is mac is 10.14.4 and my fs is APFS

**Comment by LinusU** [comment]
Seems like the C-call is returning EPERM...

> Attributes cannot be associated with this type of object. For example, attributes are not allowed for resource forks.

Is the `filepath` pointing to a normal file?

**Comment by Leaking** [comment]
yep! it's a normal file.
And i have another problem, I use this library in my electron project, when my project build in Windows, there are some errors happen,
```
error fs-xattr@0.2.1: The platform "win32" is incompatible with this module.
```

**Comment by LinusU** [comment]
This is expected, the win32 platform isn't supported at this time, track that here: #16

**Comment by Leaking** [comment]
I know it, but when i use fs-xattr in cross-platform project liked Electron, it need to be included in both Os x and win32.

track that here: #30

**Comment by Leaking** [comment]
I have fixed my problem, just use optionalDependencies instead of dependencies

**Comment by Leaking** [comment]
> yep! it's a normal file.
> And i have another problem, I use this library in my electron project, when my project build in Windows, there are some errors happen,
> 
> ```
> error fs-xattr@0.2.1: The platform "win32" is incompatible with this module.
> ```

I have fixed my problem, just use optionalDependencies instead of dependencies
