### ISSUE TITLE
when I put the fs-xattr in optionalDependcies, the xattr.node is not found.

### ISSUE THREAD

**Issue by Leaking** [LinusU/fs-xattr#31]
my fx-xattr version is 0.3.0, and I use it in my eletron project and put it under optionalDependcies.

and then I use `yarn build` to generate a dmg, and when I send the dmg to annother compute to install and run it,  i come acroos the below error.

it seems that it use absolute path in the package result.
```
error is:  
{ Error: Cannot open /Users/quinn/Documents/workspace/electron/ElectronProject/src/node/fs-xattr/build/Release/xattr.node:
  Error: dlopen(/Users/quinn/Documents/workspace/electron/ElectronProject/src/node/fs-xattr/build/Release/xattr.node, 1): image not found
    at Object.<anonymous> (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:64141:212)
    at Object.module.exports.module.exports (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:64142:30)
    at __webpack_require__ (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:21:30)
    at Object.<anonymous> (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:64062:15)
    at __webpack_require__ (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:21:30)
    at Object.createSparseFileForMac (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:24727:21)
    at Object.createSparseFile (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:24712:12)
    at /Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:6648:92
    at Generator.next (<anonymous>)
    at step (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:6608:191)
  [stack]:
   'Error: Cannot open /Users/quinn/Documents/workspace/electron/ElectronProject/src/node/fs-xattr/build/Release/xattr.node: Error: dlopen(/Users/quinn/Documents/workspace/electron/ElectronProject/src/node/fs-xattr/build/Release/xattr.node, 1): image not found\n    at Object.<anonymous> (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:64141:212)\n    at Object.module.exports.module.exports (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:64142:30)\n    at __webpack_require__ (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:21:30)\n    at Object.<anonymous> (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:64062:15)\n    at __webpack_require__ (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:21:30)\n    at Object.createSparseFileForMac (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:24727:21)\n    at Object.createSparseFile (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:24712:12)\n    at /Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:6648:92\n    at Generator.next (<anonymous>)\n    at step (/Applications/MyElectron.app/Contents/Resources/app.asar/dist/electron/node.js:6608:191)',
  [message]:
   'Cannot open /Users/quinn/Documents/workspace/electron/ElectronProject/src/node/fs-xattr/build/Release/xattr.node: Error: dlopen(/Users/quinn/Documents/workspace/electron/ElectronProject/src/node/fs-xattr/build/Release/xattr.node, 1): image not found' }
<
```

**Comment by LinusU** [comment]
Could you try to run `npm rebuild`?

**Comment by LinusU** [comment]
closing for lack of response...

**Comment by Ulyanov-programmer** [comment]
It's time to rediscover the issue!

I faced a similar problem. Execution steps:

1. I installed the **latest version** from NPM on my project, which uses `Yarn` with `PnP` technology.
2. I'm trying to import functions into one of the project files:
`import { getAttribute, setAttribute } from 'fs-xattr'`
3. I launch the project (command `yarn start`) and catch the error:
``` powershell
C:\multitool\.pnp.cjs:12877
      Error.captureStackTrace(firstError);
            ^

Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: C:\multitool\.yarn\unplugged\fs-xattr-npm-0.4.0-8e62613e09\node_modules\fs-xattr\build\Release\xattr
Not found: C:\multitool\.yarn\unplugged\fs-xattr-npm-0.4.0-8e62613e09\node_modules\fs-xattr\build\Release\xattr
Not found: C:\multitool\.yarn\unplugged\fs-xattr-npm-0.4.0-8e62613e09\node_modules\fs-xattr\build\Release\xattr.js
Not found: C:\multitool\.yarn\unplugged\fs-xattr-npm-0.4.0-8e62613e09\node_modules\fs-xattr\build\Release\xattr.json
Not found: C:\multitool\.yarn\unplugged\fs-xattr-npm-0.4.0-8e62613e09\node_modules\fs-xattr\build\Release\xattr.node

Require stack:
- C:\multitool\.yarn\unplugged\fs-xattr-npm-0.4.0-8e62613e09\node_modules\fs-xattr\index.js
    at require$$0.Module._resolveFilename (C:\multitool\.pnp.cjs:12877:13)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at require$$0.Module._load (C:\multitool\.pnp.cjs:12768:31)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at file:///C:/multitool/.yarn/unplugged/fs-xattr-npm-0.4.0-8e62613e09/node_modules/fs-xattr/index.js:3:45      
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)

Node.js v21.7.1
```

It does look like a path error, but I'm just guessing.
You can read the code in which the action takes place [here](https://github.com/Ulyanov-programmer/gulp_multitool/tree/node-based) (**THE `node-based` BRANCH!**).
The [file](https://github.com/Ulyanov-programmer/gulp_multitool/blob/node-based/plugins/comparer.js) where the functions are imported.

_And yes, don't be surprised by the mess in the code, this version is in development..._
